### PR TITLE
improved platform names

### PR DESCRIPTION
**Pull request by 4ch1m**
Hey there,

first off, thanks a lot for providing this repository! :bow: 

The `arcace/Platform/jt*.json` files are being used by [Matt Pannella](https://github.com/mattpannella)'s [Analogue Pocket Updater Utility](https://github.com/mattpannella/pocket-updater-utility); providing better names for all `jt`-cores.

I'm currently trying to implement this feature for my own [Ansible Analogue Pocket](https://github.com/4ch1m/ansible-analogue-pocket) project as well.

However, some of the names are not quite "correct".

e.g.

```
Konami (Aliens)
Konami Simpsons
Konami TMNT
```

These games will be sorted in alongside all other arcades/games starting with `K`.
Which isn't ideal when navigating/browsing the Pocket's menu.

This PR will fix this.

Again... thank you very much!

### CODE REVIEW

**Comment by dyreschlock** [comment]
Hello :)

For these cores, I used this naming scheme because they were multi-game cores rather than single game cores. All of the games in the "Arcade Multi" category start with the developer whether it's "Capcom CPS1" or "Sega System 16" or "Konami Aliens." Obviously the Aliens board isn't as expansive as CPS1 or System 16, but if those names were to change, I would suggest putting them in the regular "Arcade" category. But then, I feel like some of the other games on that core would get lost in the shuffle. Super Contra is just as notable as Alien, if not moreso, for example.

Although, looking through the platform names now, they aren't totally consistent. (Some have the parenthesis and some don't)

**Comment by 4ch1m** [comment]
I see. Thanks for the explanation!

I checked it again and just realized that the original platform-files provided by Jotego are categorized just as `Arcade`:

```
{
	"platform":{
		"category": "Arcade",
		"name": "jtaliens",
		"year": 2024,
		"manufacturer": "JT FPGA"
	}
}
```

Whereas your files are "re-categorized" as `Arcade Multi`:

```
{
  "platform": {
    "name": "Konami (Aliens)",
    "category": "Arcade Multi",
    "manufacturer": "Konami",
    "year": 1990
  }
}
```

That makes sense.

However, I think the (display-)names should not be (mis)used for the sake of "sub-grouping" in a UI, but always reflect the actual name of the arcade machine.

I guess the average Pocket user is opening the respective menu (`Arcade` or `Arcade Multi`); and tries to find "Teenage Mutant Ninja Turtles" by scrolling the alphabetically sorted list to `T`... and not to `K`.
This is not much of an issue with the `Multi Arcade`-category since there are only a few cores available; but if things are listed in the general `Arcade`-category then you have a lot of scrolling/searching to do.

That's what happened in my case. I just used the (better) names from your files, but everything else (including category) remained as provided by Jotego.

So... I'm also not sure which approach is best. :laughing: 

Generally I would not include the manufacturer in the name; also not in the `Arcade Multi` category. (So this PR is still valid. *lol*)
To be honest... I personally don't even care if it is a "Multi Arcade" or a regular "Arcade".
It's all just "Arcade" to me... I look for a game(name) and play.

But... of course... it's up to how you want to handle this.

I'll have to find my own way dealing with the categories.

Again... thanks for the explanation!

**Comment by dyreschlock** [comment]
Sure thing :)

Overall, I don't really like the term "Arcade Multi" I think "Arcade Systems" sounds a bit better, especially when some of these boards have actual names, like CPS1, System 16, or Irem's M92. But then it doesn't exactly describe what's going on with those Konami boards, the Tecmo board, the Namco boards, or the Williams boards.

The Coin-Op Collection folks have taken the approach of Single game cores only. Using their philosophy, each game in the Konami Aliens core would have their own core and be put in the Arcade category.

This would solve both problems. "Arcade Systems" would be actual arcade systems, and the names of the cores would be the actual name of the game.

But the new problem is that the Arcade category continues to grow and grow. It gets to be too much if you have all available cores installed at once and still want some kind of curation.

Some of us have gone the opposite route as Coin-Op and created multi-game combination cores from single cores that have been released. espoix has combined both System 16A and System 16B cores together for a single System 16 core. I made a Toaplan V2 core that combines all of those Raizing shooters and the Toaplan games that use the same Hardware. For many of his unreleased cores, Boogerman wants to try and consolidate as many games into a single core as possible to reduce the noise of the Arcade category.

Another approach is making more categories to split the Arcade stuff. On my personal Pocket, I used two Arcade categories for a while: one for older Arcade games and one for newer ones. (I named them Arcade Classic and Arcade Modern.) But, I like having the simple 6 categories on the main openFPGA screen. And also having to remember which games were in which category was annoying.

There are multiple ways of doing things, and, as you mentioned, there's no real best approach. :)

**Comment by 4ch1m** [comment]
I've implemented a way to define [custom core names](https://github.com/4ch1m/ansible-analogue-pocket/commit/5d8aea2625accb0394f1f97b9f53f0b6845effc9) in my project.

This way I can keep using your for most of the names; and mix in a few improvements on my own. :heavy_check_mark:

**Pull request closed without merging**
